---
title: "Explaining the Gibbs Sampler"
output:
  html_document:
    toc: yes
    toc_depth: 3
---
```{r setup, echo=FALSE}
knitr::opts_chunk$set(eval = TRUE,
echo = FALSE,
cache = FALSE,
include = TRUE,
collapse = TRUE,
warning = FALSE,
message = FALSE,
dependson = NULL,
engine = "R", # Chunks will always have R code, unless noted
error = TRUE,
fig.path="Figures/nas_mwph", # Set the figure optins
fig.align = "center",
fig.width = 6,
fig.height = 6,
dpi = 300)
```

```{r}
library(tidyr)
library(ggplot2)
library(rmutil)
library(truncdist)
library(fitdistrplus)
```
## Example1: Histogram of samples obtained using Gibbs sampling and beta-binomial distribution
```{r}
set.seed(1)
gibbs_seq <- function (m, n, k, alpha, beta, y0) {
it <- 0
a <- numeric(m)
for (j in 1:m) {
  xk <- vector()
y <- y0
for (i in 1:k) {
x <- rbinom(1, n, y)
y <- rbeta(1, x+alpha, n-x+beta, ncp = 0)
xk[i] <- x
}
  a[j] <- xk[k]
  }
  return(a)
  }
# m independent sequences of length k, choose the final value
#n = 16, alpha = 2, and beta = 4
gibbs_seq <- gibbs_seq(m=5000, n=16, k=10, alpha=2, beta=4, y0=1)
true_betabinom <- rbetabinom(5000, 16, 1/3, 6) 
#sm=alpha,s(1-m)=beta
DF <- data.frame(gibbs_seq, true_betabinom)
DF %>% 
  gather(key=Type, value=Value) %>% 
  ggplot(aes(x=Value,fill=Type)) + 
  geom_histogram(position="dodge", bins=40)
```
## Example2: Histogram of Gibbs sampling, true marginal distribution and an estimate of the marginal density
```{r}
set.seed(1)
#/(1-exp(-B*y))
B=5
gibbs2 <- function (m, k, y0, B) {
it <- 0
a <- numeric(m)
b <- numeric(m)
est <- numeric(m)
z <- matrix(ncol=2, nrow=m)
for (j in 1:m) {
  #set.seed (1)
  xk <- vector()
  yk <- vector()
y <- y0
for (i in 1:k) {
x <- rtrunc(1, spec='exp', a = 0, b = B, rate = y)
y <- rtrunc(1, spec='exp', a = 0, b = B, rate = x)
xk[i] <- x
yk[i] <- y
}
  a[j] <- xk[k]
  b[j] <- yk[k]
  est[j] <- mean(rtrunc(1, spec='exp', a = 0, b = B, rate = b[j]))
}
z <- cbind(a, est)
  return(z)
  }
# m independent sequences of length k, choose the final value
z <- gibbs2(m=500, k=15, y0=1, B=5)
z <- as.data.frame(z)
z <- data.frame(gibbs=z[,1], estimate=z[,2])
gibbs=z[,1]
estimate=z[,2]

true_density <- function(x) (1-exp(-B*x))/x
integrate(true_density, lower = 0, upper = B)

true_density <- function(x) (1-exp(-B*x))/x/3.796091

# scale <- sum(hist(gibbs, probability = TRUE, breaks = 50)$density)
# hist(gibbs, probability = TRUE, breaks = 50)
# lines(density(estimate),col="red")
# curve(true_density,add=TRUE, col="blue")

z %>%
  gather(key=Type, value=Value) %>%
  ggplot(aes(x=Value,fill=Type)) +
  geom_histogram(aes(y =..density..), position="dodge", bins=50)+
  stat_function(fun=true_density)
```


## Example 1(continued)
```{r}
set.seed(1)
gibbs_est <- function (m, n, k, alpha, beta, y0) {
it <- 0
a <- numeric(m)
b <- numeric(m)
est <- numeric(m)
for (j in 1:m) {
  xk <- vector()
  yk <- vector()
  y <- y0
for (i in 1:k) {
x <- rbinom(1, n, y)
y <- rbeta(1, x+alpha, n-x+beta, ncp = 0)
xk[i] <- x
yk[i] <- y

}
  a[j] <- xk[k]
  b[j] <- yk[k]
  est[j] <- mean(rbinom(1, n, b[j]))
  }
  return(est)
  }
# m independent sequences of length k, choose the final value
#n = 16, alpha = 2, and beta = 4
gibbs_est <- gibbs_est(m=500, n=16, k=10, alpha=2, beta=4, y0=1)
true_betabinom <- rbetabinom(500, 16, 1/3, 6) 
DF <- data.frame(gibbs_est, true_betabinom)
DF %>% 
  gather(key=Type, value=Value) %>% 
  ggplot(aes(x=Value,fill=Type)) + 
  geom_histogram(position="dodge", bins=40)
```

## Example 2 (continued)
```{r}
set.seed(1)
gibbs_exp <- function (m, k,  y0) {
it <- 0
a <- numeric(m)
for (j in 1:m) {
  xk <- vector()
y <- y0
for (i in 1:k) {
x <- rexp(1, rate=y)
y <- rexp(1, rate=x)
xk[i] <- x
}
  a[j] <- xk[k]
  }
  return(a)
  }
# m independent sequences of length k, choose the final value
#n = 16, alpha = 2, and beta = 4
gibbs_exp <- gibbs_exp(m=500, k=10, y0=2)
x <- gibbs_exp[gibbs_exp<15]
gibbs_exp <- data.frame(x=x)
ggplot(gibbs_exp, aes(x = x, y = ..density..)) +
  geom_histogram(binwidth = 0.1) +
  labs(title = "Histogram of a sample of size m = 500 from the conditional Distributions in example2", x = "x", y = "probability")
```

## Estimates of probabilities of the marginal distribution of X.
```{r}
set.seed(1)
gibbs3 <- function (m, n, k, alpha, beta, y0, z0) {
it <- 0
a <- numeric(m)
b <- numeric(m)
est <- numeric(m)
for (j in 1:m) {
  yk <- vector()
  zk <- vector()
  y <- y0
  z <- z0
for (i in 1:k) {
x <- rbinom(1, z, y)
y <- rbeta(1, x+alpha, z-x+beta, ncp = 0)
z <- rpois(1, (1-y)*16)+x
yk[i] <- y
zk[i] <- z
}
  a[j] <- yk[k]
  b[j] <- zk[k]
  est[j] <- mean(rbinom(1, b[j], a[j]))
  }
  return(est)
  }
gibbs3 <- data.frame(x=gibbs3(m=500, k=10, alpha=2, beta=4, y0=1, z0=1))
ggplot(gibbs3, aes(x = x, y = ..density..)) +
  geom_histogram(binwidth = 0.5) +
  labs(title = "Marginal distribution of X", x = "x", y = "probability")
```


